macro(ddd_config config_name default_value config_type config_description)
	if("${${config_name}}" STREQUAL "")
		set(${config_name} ${default_value} CACHE ${config_type} "${config_description}")
	endif()
	separate_arguments(${config_name})
	set(_val ${${config_name}})
	set(${config_name} ${val} CACHE ${config_type} "${config_description}")
	message(STATUS "Config ${config_name} (${config_description}) is set to \"${_val}\"")
	target_compile_definitions(${PROJECT_NAME}Common INTERFACE ${config_name})
endmacro()
